# Generated by Django 5.1.3 on 2024-12-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='Код'),
        ),
    ]
