# Generated by Django 5.1.3 on 2024-12-07 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
        ('federations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='federation',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.region', verbose_name='Регион'),
        ),
    ]
