# Generated by Django 5.1.3 on 2024-12-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federations', '0002_federation_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='federation',
            name='logo',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка на лого'),
        ),
    ]
