# Generated by Django 5.1.3 on 2024-12-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federations', '0003_federation_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federation',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Электронная почта'),
        ),
    ]
