# Generated by Django 5.1.3 on 2024-12-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federations', '0004_alter_federation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federation',
            name='name',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='Наименование'),
        ),
    ]
