# Generated by Django 5.1.3 on 2024-12-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestant', '0002_remove_contestant_age_group_remove_team_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, max_length=300, null=True, to='contestant.contestant', verbose_name='Члены команды'),
        ),
    ]
