# Generated by Django 5.1.3 on 2024-12-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestant', '0003_remove_team_members_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Члены команды'),
        ),
    ]
