# Generated by Django 5.1.3 on 2024-12-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claim_end_time_claim_format_claim_name_claim_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Название заявки'),
        ),
    ]
