# Generated by Django 5.1.3 on 2024-12-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_alter_claim_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('ONPROGRESS', 'На рассмотрении'), ('MODERATE', 'Отправлен на модерацию'), ('REJECTED', 'Отклонен'), ('ACCEPTED', 'Принят')], default='NEW', max_length=25, verbose_name='Статус'),
        ),
    ]
