# Generated by Django 5.1.3 on 2024-12-07 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_claim_status'),
        ('federations', '0002_federation_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='receiver_federation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Приниматель', to='federations.federation'),
        ),
        migrations.AddField(
            model_name='claim',
            name='sender_federation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Отправитель', to='federations.federation'),
        ),
    ]
