# Generated by Django 5.1.3 on 2024-12-07 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_claim_receiver_federation_claim_sender_federation'),
        ('contests', '0005_contest_contest_char_alter_contest_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='contest_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.contesttype', verbose_name='Уровень соревнования'),
        ),
    ]
