# Generated by Django 5.1.3 on 2024-12-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_rename_claim_contest_char_claim_contest_char_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='end_time',
            field=models.DateTimeField(verbose_name='Дата окончания'),
        ),
    ]
