# Generated by Django 5.1.3 on 2024-12-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0009_alter_claim_end_time_alter_claim_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='contest_char',
            field=models.CharField(choices=[('Личная', 'Личная'), ('Командная', 'Командная')], db_index=True, default='Личная', max_length=11, verbose_name='Характер соревнования'),
        ),
    ]
