# Generated by Django 5.1.3 on 2024-12-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0010_alter_claim_contest_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='file',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка на файл'),
        ),
    ]
