# Generated by Django 5.1.3 on 2024-12-08 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0011_claim_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='file',
        ),
    ]
