# Generated by Django 5.1.3 on 2024-12-06 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Уровень соревнования')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Вид спорта')),
            ],
        ),
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Вид спорта')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=250, verbose_name='Программа')),
                ('code', models.CharField(max_length=250, verbose_name='Код')),
                ('start', models.DateField(verbose_name='Дата начала')),
                ('end', models.DateField(verbose_name='Дата окончания')),
                ('contestants', models.IntegerField(verbose_name='Количество участников')),
                ('male', models.BooleanField(verbose_name='Мужчины')),
                ('female', models.BooleanField(verbose_name='Женщины')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.country', verbose_name='Страна проведения')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.city', verbose_name='Город проведения')),
                ('contest_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.contesttype', verbose_name='Уровень соревнования')),
            ],
        ),
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(0, 'Женщина'), (1, 'Мужчина')], default=1, verbose_name='Пол')),
                ('start', models.IntegerField(verbose_name='Нижний порог')),
                ('end', models.IntegerField(verbose_name='Верхний порог')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest', verbose_name='Cоревнование')),
            ],
        ),
        migrations.CreateModel(
            name='ContestDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.contest', verbose_name='Cоревнование')),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.discipline', verbose_name='Дисциплина')),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='sport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.sporttype', verbose_name='Вид спорта'),
        ),
    ]
