# Generated by Django 5.1.3 on 2024-12-06 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agegroup',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='code',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='contestants',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='end',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='female',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='male',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='program',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='start',
        ),
        migrations.AddField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(default='2024-01-01 15:00', verbose_name='Дата окончания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='format',
            field=models.CharField(choices=[('ONLINE', 'Онлайн'), ('OFFLINE', 'Оффлайн'), ('ONLINE/OFFLINE', 'Онлайн/Оффлайн')], default='ONLINE', max_length=20, verbose_name='Формат соревнования'),
        ),
        migrations.AddField(
            model_name='contest',
            name='name',
            field=models.CharField(default='', max_length=300, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(default='2024-01-01 15:00', verbose_name='Дата начала'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ContestAgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.agegroup', verbose_name='Возрастная группа')),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.contest', verbose_name='Cоревнование')),
            ],
        ),
    ]
