# Generated by Django 5.1.3 on 2024-12-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_remove_agegroup_contest_remove_contest_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активный'), ('CLOSED', 'Закрыт'), ('CANCLED', 'Отменен')], default='ACTIVE', max_length=10, verbose_name='Статус'),
        ),
    ]
