# Generated by Django 5.1.3 on 2024-12-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_contest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroup',
            name='end',
            field=models.IntegerField(blank=True, null=True, verbose_name='Верхний порог'),
        ),
    ]
