# Generated by Django 5.1.3 on 2024-12-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_contest_federation_contest_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='place',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(db_index=True, verbose_name='Дата начала'),
        ),
    ]
