# Generated by Django 5.1.3 on 2024-12-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_alter_contest_end_time_alter_contest_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest_char',
            field=models.CharField(choices=[('Личная', 'Личная'), ('Командная', 'Командная')], db_index=True, default='Личная', max_length=11, verbose_name='Характер соревнования'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='place',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Город'),
        ),
    ]
