# Generated by Django 5.1.3 on 2024-12-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_alter_contest_contest_char_alter_contest_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/', verbose_name='Файл'),
        ),
    ]
