# Generated by Django 5.1.3 on 2024-12-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_alter_contest_contest_char_alter_contest_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='file',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка на файл'),
        ),
    ]
